#!/bin/bash

# 🚀 Vercel Redeploy Script
# This script helps you redeploy to Vercel with the fixed environment variable

echo ""
echo "=========================================="
echo "🚀 Vercel Redeploy - Facebook Comment Fix"
echo "=========================================="
echo ""

echo "📋 What needs to be done:"
echo "   1. Update FACEBOOK_PAGE_ID in Vercel to: 963307416870090"
echo "   2. Trigger redeployment"
echo ""

echo "🔧 Option 1: Manual Update (Recommended)"
echo "-------------------------------------------"
echo ""
echo "Step 1: Go to Vercel Dashboard"
echo "   URL: https://vercel.com/riajfreelance-ctrls-projects/metasolution/settings/environment-variables"
echo ""
echo "Step 2: Update FACEBOOK_PAGE_ID"
echo "   - Find FACEBOOK_PAGE_ID"
echo "   - Change value to: 963307416870090"
echo "   - Click 'Save'"
echo ""
echo "Step 3: Redeploy"
echo "   - Go to: https://vercel.com/riajfreelance-ctrls-projects/metasolution"
echo "   - Click on 'Deployments' tab"
echo "   - Click on the latest deployment"
echo "   - Click '...' menu and select 'Redeploy'"
echo ""

echo "🔧 Option 2: Using Vercel CLI"
echo "-------------------------------------------"
echo ""
echo "If you have Vercel CLI installed:"
echo ""
echo "   # Install Vercel CLI (if not installed)"
echo "   npm i -g vercel"
echo ""
echo "   # Login to Vercel"
echo "   vercel login"
echo ""
echo "   # Update environment variable"
echo "   vercel env add FACEBOOK_PAGE_ID production"
echo "   # Enter: 963307416870090"
echo ""
echo "   # Trigger redeploy"
echo "   vercel --prod"
echo ""

echo "🔧 Option 3: Using API Script"
echo "-------------------------------------------"
echo ""
echo "If you have a Vercel API token:"
echo ""
echo "   export VERCEL_TOKEN=your_token_here"
echo "   node fix_vercel_env_now.js"
echo ""

echo "✅ After Redeployment:"
echo "-------------------------------------------"
echo ""
echo "1. Test the comment automation:"
echo "   - Go to your Facebook page"
echo "   - Comment 'price koto?' on any post"
echo "   - Wait 5-10 seconds"
echo "   - Check if auto-reply works"
echo ""
echo "2. Monitor logs:"
echo "   - https://vercel.com/riajfreelance-ctrls-projects/metasolution/logs"
echo "   - Look for [WEBHOOK] and [COMMENT PROCESS] entries"
echo ""

echo "📊 Current Status:"
echo "-------------------------------------------"
echo "   Local .env: ✅ Updated (963307416870090)"
echo "   Vercel Env: ⚠️  Needs update"
echo "   Webhook: ✅ Working"
echo "   Token: ✅ Valid"
echo ""

echo "💡 Quick Link:"
echo "   https://vercel.com/riajfreelance-ctrls-projects/metasolution/settings/environment-variables"
echo ""
