#!/bin/bash

# 🧪 Facebook Comment Automation - Real Test Guide
# This script helps you test the automation

echo ""
echo "=========================================="
echo "🧪 Facebook Comment Automation Test Guide"
echo "=========================================="
echo ""

echo "📋 STEP 1: Check Current Status"
echo "--------------------------------"
echo ""

# Check if server is running
echo "Checking Vercel deployment status..."
curl -s -o /dev/null -w "Webhook Status: %{http_code}\n" "https://metasolution-rho.vercel.app/webhook?hub.mode=subscribe&hub.verify_token=myapp4204&hub.challenge=test"

echo ""
echo "📋 STEP 2: Test Instructions"
echo "----------------------------"
echo ""
echo "Follow these steps to test:"
echo ""
echo "1️⃣  Go to your Facebook Page (Skinzy)"
echo "   URL: https://facebook.com/963307416870090"
echo ""
echo "2️⃣  Create a test post (or use existing one)"
echo "   Example post: 'নতুন প্রোডাক্ট এসেছে! 🎉'"
echo ""
echo "3️⃣  Test these comments (one by one):"
echo ""
echo "   Test #1 - Price Inquiry:"
echo "   Comment: 'price koto?'"
echo "   Expected: Auto reply with price info"
echo ""
echo "   Test #2 - Order Request:"
echo "   Comment: 'order korbo'"
echo "   Expected: Auto reply with order instructions"
echo ""
echo "   Test #3 - Delivery Question:"
echo "   Comment: 'delivery koto din?'"
echo "   Expected: Auto reply with delivery time"
echo ""
echo "   Test #4 - Positive Feedback (Catch-All):"
echo "   Comment: 'অনেক ভালো প্রোডাক্ট!'"
echo "   Expected: Thank you reply (catch-all)"
echo ""
echo "   Test #5 - Greeting:"
echo "   Comment: 'hi'"
echo "   Expected: Welcome message"
echo ""
echo "   Test #6 - Random Comment (AI Test):"
echo "   Comment: 'এইটা কি real না fake?'"
echo "   Expected: AI-generated reply"
echo ""

echo "📋 STEP 3: Monitor Results"
echo "--------------------------"
echo ""
echo "After commenting, check these:"
echo ""
echo "✅ Facebook Post:"
echo "   - Public reply should appear under your comment"
echo "   - Comment should be auto-liked ❤️"
echo ""
echo "✅ Facebook Messenger:"
echo "   - Private reply should come to inbox"
echo "   - Message from Skinzy page"
echo ""
echo "✅ Firestore Database:"
echo "   - Collection: 'comments' → New entry for each comment"
echo "   - Collection: 'leads' → Lead captured"
echo "   - Collection: 'raw_webhooks' → Webhook received"
echo ""

echo "📋 STEP 4: Check Logs"
echo "---------------------"
echo ""
echo "To check what's happening:"
echo ""
echo "Option 1: Vercel Logs (Real-time)"
echo "  Command: vercel logs --follow"
echo ""
echo "Option 2: Check Firestore"
echo "  - Go to Firebase Console"
echo "  - Navigate to Firestore Database"
echo "  - Check collections:"
echo "    • comments (processed comments)"
echo "    • pending_comments (unmatched comments)"
echo "    • raw_webhooks (incoming webhooks)"
echo "    • logs (system logs)"
echo ""

echo "📋 STEP 5: Troubleshooting"
echo "--------------------------"
echo ""
echo "If comments are NOT getting replies:"
echo ""
echo "❌ Problem: No webhook received"
echo "   Solution: Check Facebook App webhook subscription"
echo "   Run: node server/check_app_webhooks.js"
echo ""
echo "❌ Problem: Comment goes to pending"
echo "   Solution: Add keyword to comment_drafts"
echo "   Or check if catch-all drafts have valid replies"
echo ""
echo "❌ Problem: Token expired"
echo "   Solution: Renew Facebook Page Access Token"
echo "   Check brand document in Firestore"
echo ""
echo "❌ Problem: Rate limit error"
echo "   Solution: Wait a few minutes, then retry"
echo "   Facebook has API call limits"
echo ""

echo "=========================================="
echo "🎯 Quick Test Commands"
echo "=========================================="
echo ""
echo "Run diagnostic:"
echo "  node server/diagnose_comment.js"
echo ""
echo "Run automation test:"
echo "  node server/test_comment_automation.js"
echo ""
echo "Check webhook status:"
echo "  node server/check_app_webhooks.js"
echo ""
echo "List brands:"
echo "  node server/list_brands.js"
echo ""
echo "=========================================="
echo "✅ Ready to test!"
echo "=========================================="
echo ""
echo "Start with Test #1 and let me know the results!"
echo ""
