#!/bin/bash
# Test Comment Automation After Fix

echo "🧪 Testing Comment Automation Fix"
echo "=================================="
echo ""

echo "✅ Fix Applied:"
echo "   - Fast keyword matching (no more slow fuzzy search first)"
echo "   - Timeout increased from 30s to 50s"
echo "   - Optimized database queries"
echo ""

echo "📝 How to Test:"
echo "================"
echo ""
echo "1. Go to your Facebook page: https://facebook.com/YourPage"
echo ""
echo "2. Find any post and comment with ONE of these:"
echo "   • price / দাম / price? / dam koto"
echo "   • order / অর্ডার / order korbo"
echo "   • delivery / ডেলিভারি / delivery charge"
echo "   • available / stock / আছে"
echo "   • discount / ছাড় / offer"
echo ""
echo "3. Expected Result (within 5-15 seconds):"
echo "   ✅ Public reply on your comment"
echo "   ✅ Private message in your inbox"
echo ""
echo "4. If it still doesn't work, check:"
echo "   curl https://metasolution-rho.vercel.app/api/health/webhook"
echo "   curl https://metasolution-rho.vercel.app/api/health/automation"
echo ""
echo "🚀 Deployment is LIVE! Try commenting now."
